FROM debian:12.7

ENV SECRET_KEY=${SECRET_KEY:-elsecretodetusojosdocker}
ENV DB_DIR_PATH=${DB_DIR_PATH:-./archivos-proyecto/db/}
ENV EXCEL_RESULTS_DIR_PATH=${EXCEL_RESULTS_DIR_PATH:-./archivos-proyecto/excel_results/}
ENV DOMAIN_OPT_SERVER=${DOMAIN_OPT_SERVER:-localhost}
ENV INVITED_PASS=${INVITED_PASS:-alimentos.saludables.ceape}

EXPOSE 5000

# Establecer el directorio de trabajo en el contenedor
WORKDIR /root

# Copiar el directorio archivos-proyecto desde el servidor local al contenedor
COPY ./archivos-proyecto/ /root/archivos-proyecto/

# Instalamos los paquetes de python3 necesarios para manejar los entornos virtuales
RUN apt-get update && \
    apt-get install -y python3-venv

# Creamos un entorno virtual en la carpeta /root
RUN python3 -m venv ENV

# Instalamos los paquetes de Python necesarios en el entorno virtual
RUN /root/ENV/bin/python -m pip install -r /root/archivos-proyecto/requirements.txt

# Establecer Bash como el shell predeterminado
CMD ["/bin/bash"]
